apiVersion: tests.testkube.io/v1
kind: TestTrigger
metadata:
  name: testtrigger-example
  namespace: testkube
spec:
  resource: deployment
  resourceSelector:
    labelSelector:
      matchLabels:
        environment: production
  event: deployment-scale-update
  conditionSpec:
    timeout: 100
    conditions:
    - type: Available
      status: "True"
  action: run
  execution: testsuite
  testSelector:
    name: foass-testsuite
    namespace: testkube
