apiVersion: apps/v1
kind: Deployment
metadata:
  name: foass-deployment
  namespace: foass
  labels:
    environment: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: foass-pod
  template:
    metadata:
      labels:
        app: foass-pod
    spec:
      containers:
      - name: foass
        image: samaarah1docker/foass:latest
        ports:
        - name: http
          containerPort: 5000
---
kind: Service
apiVersion: v1
metadata:
  name: foass-service
  namespace: foass
spec:
  selector:
    app: foass-pod
  ports:
  - protocol: TCP
    port: 5000
    targetPort: http
---
apiVersion: v1
kind: Pod 
metadata: 
  name: foass-pod
  namespace: foass
spec:
  containers:
  - name: foass
    image: samaarah1docker/foass:latest
