apiVersion: v1
kind: Service
metadata:
  name: foass-service
  namespace: foass
spec:
  type: NodePort
  ports:
  - port: 3000
  selector:
    app: foass-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: foass-deployment
  namespace: foass
  labels:
    app: foass-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: foass-app
  template:
    metadata:
      labels:
        app: foass-app
    spec:
      containers:
      - name: foass
        image: samaarah1docker/foass:latest
        ports:
        - containerPort: 80
